namespace WinFormsLib
{
    public static class Chars
    {
        public const char NULL = '\0'; // [null]
        public const char ESCAPE = '\x1B'; // [esc]
        public const char HORIZONTAL_TAB = '\t'; // \t
        public const char LINE_FEED = '\n'; // \n
        public const char SPACE = ' '; // [space]
        public const char EXCLAMATION_MARK = '!'; // !
        public const char DOUBLE_QUOTE = '"'; // "
        public const char NUMBER_SIGN = '#'; // #
        public const char DOLLAR_SIGN = '$'; // $
        public const char PERCENT_SIGN = '%'; // %
        public const char AMPERSAND = '&'; // &
        public const char SINGLE_QUOTE = '\''; // '
        public const char LEFT_ROUND_BRACKET = '('; // (
        public const char RIGHT_ROUND_BRACKET = ')'; // )
        public const char ASTERISK = '*'; // *
        public const char PLUS_SIGN = '+'; // +
        public const char COMMA = ','; // ,
        public const char HYPHEN = '-'; // -
        public const char PERIOD = '.'; // .
        public const char SLASH = '/'; // /
        public const char ZERO = '0'; // 0
        public const char ONE = '1'; // 1
        public const char TWO = '2'; // 2
        public const char THREE = '3'; // 3
        public const char FOUR = '4'; // 4
        public const char FIVE = '5'; // 5
        public const char SIX = '6'; // 6
        public const char SEVEN = '7'; // 7
        public const char EIGHT = '8'; // 8
        public const char NINE = '9'; // 9
        public const char COLON = ':'; // :
        public const char SEMICOLON = ';'; // :
        public const char LESS_THAN_SIGN = '<'; // <
        public const char EQUALS_SIGN = '='; // =
        public const char GREATER_THAN_SIGN = '>'; // >
        public const char QUESTION_MARK = '?'; // ?
        public const char AT_SIGN = '@'; // @
        public const char A_UPPER = 'A'; // A
        public const char B_UPPER = 'B'; // B
        public const char C_UPPER = 'C'; // C
        public const char D_UPPER = 'D'; // D
        public const char E_UPPER = 'E'; // E
        public const char F_UPPER = 'F'; // F
        public const char G_UPPER = 'G'; // G
        public const char H_UPPER = 'H'; // H
        public const char I_UPPER = 'I'; // I
        public const char J_UPPER = 'J'; // J
        public const char K_UPPER = 'K'; // K
        public const char L_UPPER = 'L'; // L
        public const char M_UPPER = 'M'; // M
        public const char N_UPPER = 'N'; // N
        public const char O_UPPER = 'O'; // O
        public const char P_UPPER = 'P'; // P
        public const char Q_UPPER = 'Q'; // Q
        public const char R_UPPER = 'R'; // R
        public const char S_UPPER = 'S'; // S
        public const char T_UPPER = 'T'; // T
        public const char U_UPPER = 'U'; // U
        public const char V_UPPER = 'V'; // V
        public const char W_UPPER = 'W'; // W
        public const char X_UPPER = 'X'; // X
        public const char Y_UPPER = 'Y'; // Y
        public const char Z_UPPER = 'Z'; // Z
        public const char LEFT_SQUARE_BRACKET = '['; // [
        public const char BACKSLASH = '\\'; // \
        public const char RIGHT_SQUARE_BRACKET = ']'; // ]
        public const char CARET = '^'; // ^
        public const char UNDERSCORE = '_'; // _
        public const char GRAVE_ACCENT = '`'; // `
        public const char A_LOWER = 'a'; // a
        public const char B_LOWER = 'b'; // b
        public const char C_LOWER = 'c'; // c
        public const char D_LOWER = 'd'; // d
        public const char E_LOWER = 'e'; // e
        public const char F_LOWER = 'f'; // f
        public const char G_LOWER = 'g'; // g
        public const char H_LOWER = 'h'; // h
        public const char I_LOWER = 'i'; // i
        public const char J_LOWER = 'j'; // j
        public const char K_LOWER = 'k'; // k
        public const char L_LOWER = 'l'; // l
        public const char M_LOWER = 'm'; // m
        public const char N_LOWER = 'n'; // n
        public const char O_LOWER = 'o'; // o
        public const char P_LOWER = 'p'; // p
        public const char Q_LOWER = 'q'; // q
        public const char R_LOWER = 'r'; // r
        public const char S_LOWER = 's'; // s
        public const char T_LOWER = 't'; // t
        public const char U_LOWER = 'u'; // u
        public const char V_LOWER = 'v'; // v
        public const char W_LOWER = 'w'; // w
        public const char X_LOWER = 'x'; // x
        public const char Y_LOWER = 'y'; // y
        public const char Z_LOWER = 'z'; // z
        public const char LEFT_CURLY_BRACE = '{'; // {
        public const char VERTICAL_BAR = '|'; // |
        public const char RIGHT_CURLY_BRACE = '}'; // }
        public const char TILDE = '~'; // ~
        public const char DELETE = '\u007f'; // [del]
        public static readonly char EURO_SIGN = '\u0080'; // €
        public static readonly char LEFT_CURLY_SINGLE_QUOTE_LOW = '\u0082'; // ‚
        public static readonly char FLORIN_SIGN = '\u0083'; // ƒ
        public static readonly char LEFT_CURLY_DOUBLE_QUOTE_LOW = '\u0084'; // „
        public static readonly char ELLIPSES = '\u0085'; // …
        public static readonly char DAGGER = '\u0086'; // †
        public static readonly char DOUBLE_DAGGER = '\u0087'; // ‡
        public static readonly char CIRCUMFLEX_ACCENT = '\u0088'; // ˆ
        public static readonly char PER_MILLE = '\u0089'; // ‰
        public static readonly char S_CARON_UPPER = '\u008a'; // Š
        public static readonly char LEFT_ANGLE_SINGLE_QUOTE = '\u008b'; // ‹
        public static readonly char OE_LIG_UPPER = '\u008c'; // Œ
        public static readonly char Z_CARON_UPPER = '\u008e'; // Ž
        public static readonly char LEFT_CURLY_SINGLE_QUOTE = '\u0091'; // ‘
        public static readonly char RIGHT_CURLY_SINGLE_QUOTE = '\u0092'; // ’
        public static readonly char LEFT_CURLY_DOUBLE_QUOTE = '\u0093'; // “
        public static readonly char RIGHT_CURLY_DOUBLE_QUOTE = '\u0094'; // ”
        public static readonly char BULLET = '\u0095'; // •
        public static readonly char EN_DASH = '\u0096'; // –
        public static readonly char EM_DASH = '\u0097'; // —
        public static readonly char TILDE_SMALL = '\u0098'; // ˜
        public static readonly char TRADEMARK_SYMBOL = '\u0099'; // ™
        public static readonly char S_CARON_LOWER = '\u009a'; // š
        public static readonly char RIGHT_ANGLE_SINGLE_QUOTE = '\u009b'; // ›
        public static readonly char OE_LIG_LOWER = '\u009c'; // œ
        public static readonly char Z_CARON_LOWER = '\u009e'; // ž
        public static readonly char Y_TREMA_UPPER = '\u009f'; // Ÿ
        public static readonly char INVERTED_EXCLAMATION = '¡'; // ¡
        public static readonly char CENT_SIGN = '¢'; // ¢
        public static readonly char POUND_STERLING = '£'; // £
        public static readonly char GENERAL_CURRENCY_SIGN = '¤'; // ¤
        public static readonly char YEN_SIGN = '¥'; // ¥
        public static readonly char BROKEN_VERTICAL_BAR = '¦'; // ¦
        public static readonly char SECTION_SIGN = '§'; // §
        public static readonly char UMLAUT = '¨'; // ¨
        public static readonly char COPYRIGHT = '©'; // ©
        public static readonly char FEMININE_ORDINAL = 'ª'; // ª
        public static readonly char LEFT_ANGLE_DOUBLE_QUOTE = '«'; // «
        public static readonly char NOT_SIGN = '¬'; // ¬
        public static readonly char SOFT_HYPHEN = '­'; // (-)
        public static readonly char REGISTERED_TRADEMARK = '®'; // ®
        public static readonly char MACRON_ACCENT = '¯'; // ¯
        public static readonly char DEGREE_SIGN = '°'; // °
        public static readonly char PLUS_OR_MINUS = '±'; // ±
        public static readonly char SUPERSCRIPT_TWO = '²'; // ²
        public static readonly char SUPERSCRIPT_THREE = '³'; // ³
        public static readonly char ACUTE_ACCENT = '´'; // ´
        public static readonly char MICRO_SIGN = 'µ'; // µ
        public static readonly char PARAGRAPH_SIGN = '¶'; // ¶
        public static readonly char MIDDLE_DOT = '·'; // ·
        public static readonly char CEDILLA = '¸'; // ¸
        public static readonly char SUPERSCRIPT_ONE = '¹'; // ¹
        public static readonly char MASCULINE_ORDINAL = 'º'; // º
        public static readonly char RIGHT_ANGLE_DOUBLE_QUOTE = '»'; // »
        public static readonly char ONE_FOURTH = '¼'; // ¼
        public static readonly char ONE_HALF = '½'; // ½
        public static readonly char THREE_FOURTHS = '¾'; // ¾
        public static readonly char INVERTED_QUESTION_MARK = '¿'; // ¿
        public static readonly char A_GRAVE_ACCENT_UPPER = 'À'; // À
        public static readonly char A_ACUTE_ACCENT_UPPER = 'Á'; // Á
        public static readonly char A_CIRCUMFLEX_ACCENT_UPPER = 'Â'; // Â
        public static readonly char A_TILDE_UPPER = 'Ã'; // Ã
        public static readonly char A_UMLAUT_UPPER = 'Ä'; // Ä
        public static readonly char A_RING_UPPER = 'Å'; // Å
        public static readonly char AE_UPPER = 'Æ'; // Æ
        public static readonly char C_CEDILLA_UPPER = 'Ç'; // Ç
        public static readonly char E_GRAVE_ACCENT_UPPER = 'È'; // È
        public static readonly char E_ACUTE_ACCENT_UPPER = 'É'; // É
        public static readonly char E_CIRCUMFLEX_ACCENT_UPPER = 'Ê'; // Ê
        public static readonly char E_UMLAUT_UPPER = 'Ë'; // Ë
        public static readonly char I_GRAVE_ACCENT_UPPER = 'Ì'; // Ì
        public static readonly char I_ACUTE_ACCENT_UPPER = 'Í'; // Í
        public static readonly char I_CIRCUMFLEX_ACCENT_UPPER = 'Î'; // Î
        public static readonly char I_UMLAUT_UPPER = 'Ï'; // Ï
        public static readonly char ETH_ICELANDIC_UPPER = 'Ð'; // Ð
        public static readonly char N_TILDE_UPPER = 'Ñ'; // Ñ
        public static readonly char O_GRAVE_ACCENT_UPPER = 'Ò'; // Ò
        public static readonly char O_ACUTE_ACCENT_UPPER = 'Ó'; // Ó
        public static readonly char O_CIRCUMFLEX_ACCENT_UPPER = 'Ô'; // Ô
        public static readonly char O_TILDE_UPPER = 'Õ'; // Õ
        public static readonly char O_UMLAUT_UPPER = 'Ö'; // Ö
        public static readonly char MULTIPLICATION_SIGN = '×'; // ×
        public static readonly char O_SLASH_UPPER = 'Ø'; // Ø
        public static readonly char U_GRAVE_ACCENT_UPPER = 'Ù'; // Ù
        public static readonly char U_ACUTE_ACCENT_UPPER = 'Ú'; // Ú
        public static readonly char U_CIRCUMFLEX_ACCENT_UPPER = 'Û'; // Û
        public static readonly char U_UMLAUT_UPPER = 'Ü'; // Ü
        public static readonly char Y_ACUTE_ACCENT_UPPER = 'Ý'; // Ý
        public static readonly char THORN_ICELANDIC_UPPER = 'Þ'; // Þ
        public static readonly char SHARPS_GERMAN_LOWER = 'ß'; // ß
        public static readonly char A_GRAVE_ACCENT_LOWER = 'à'; // à
        public static readonly char A_ACUTE_ACCENT_LOWER = 'á'; // á
        public static readonly char A_CIRCUMFLEX_ACCENT_LOWER = 'â'; // â
        public static readonly char A_TILDE_LOWER = 'ã'; // ã
        public static readonly char A_UMLAUT_LOWER = 'ä'; // ä
        public static readonly char A_RING_LOWER = 'å'; // å
        public static readonly char AE_LOWER = 'æ'; // æ
        public static readonly char C_CEDILLA_LOWER = 'ç'; // ç
        public static readonly char E_GRAVE_ACCENT_LOWER = 'è'; // è
        public static readonly char E_ACUTE_ACCENT_LOWER = 'é'; // é
        public static readonly char E_CIRCUMFLEX_ACCENT_LOWER = 'ê'; // ê
        public static readonly char E_UMLAUT_LOWER = 'ë'; // ë
        public static readonly char I_GRAVE_ACCENT_LOWER = 'ì'; // ì
        public static readonly char I_ACUTE_ACCENT_LOWER = 'í'; // í
        public static readonly char I_CIRCUMFLEX_ACCENT_LOWER = 'î'; // î
        public static readonly char I_UMLAUT_LOWER = 'ï'; // ï
        public static readonly char ETH_ICELANDIC_LOWER = 'ð'; // ð
        public static readonly char N_TILDE_LOWER = 'ñ'; // ñ
        public static readonly char O_GRAVE_ACCENT_LOWER = 'ò'; // ò
        public static readonly char O_ACUTE_ACCENT_LOWER = 'ó'; // ó
        public static readonly char O_CIRCUMFLEX_ACCENT_LOWER = 'ô'; // ô
        public static readonly char O_TILDE_LOWER = 'õ'; // õ
        public static readonly char O_UMLAUT_LOWER = 'ö'; // ö
        public static readonly char DIVISION_SIGN = '÷'; // ÷
        public static readonly char O_SLASH_LOWER = 'ø'; // ø
        public static readonly char U_GRAVE_ACCENT_LOWER = 'ù'; // ù
        public static readonly char U_ACUTE_ACCENT_LOWER = 'ú'; // ú
        public static readonly char U_CIRCUMFLEX_ACCENT_LOWER = 'û'; // û
        public static readonly char U_UMLAUT_LOWER = 'ü'; // ü
        public static readonly char Y_ACUTE_ACCENT_LOWER = 'ý'; // ý
        public static readonly char THORN_ICELANDIC_LOWER = 'þ'; // þ
        public static readonly char Y_UMLAUT_LOWER = 'ÿ'; // ÿ
    }
}
