<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.0.0.7</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Authors>Raf Colson</Authors>
    <Company>RacoSoft</Company>
    <Copyright>Copyright © $([System.DateTime]::Now.ToString('yyyy')) Raf Colson (RacoSoft)</Copyright>
    <RepositoryUrl>https://github.com/rafcolson/DotNetHelper</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AdvTabControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="AdvTabPage.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="FlatComboBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Globals.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Globals.resx</DependentUpon>
    </Compile>
    <Compile Update="PanelMenu.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Globals.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Globals.Designer.cs</LastGenOutput>
      <CustomToolNamespace></CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
